export const Shadow = `shadow-[0px_4px_4px_0px_#8DB0FF25,0px_-4px_4px_0px_#8DB0FF25,4px_0px_4px_0px_#8DB0FF25,-4px_0px_4px_0px_#8DB0FF25]`;
export const Button_Gradient = `bg-linear-to-r from-primary to-[#153885]`;
export const MOCK_TOTAL_USERS_DATA = {
  total_users: 45, // Total number of users for pagination
  users: [
    // Mock user list (ensure this list is long enough to demonstrate pagination)
    {
      id: 1,
      full_name: "Alice Johnson",
      username: "alice_j",
      age: 28,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 2,
      full_name: "Bob Williams",
      username: "bob_w",
      age: 34,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 3,
      full_name: "Charlie Brown",
      username: "charlie_b",
      age: 22,
      gender: "Male",
      subscription: "Premium",
    },
    {
      id: 4,
      full_name: "Diana Prince",
      username: "diana_p",
      age: 40,
      gender: "Female",
      subscription: "Free",
    },
    {
      id: 5,
      full_name: "Ethan Hunt",
      username: "ethan_h",
      age: 30,
      gender: "Male",
      subscription: "Premium",
    },
    {
      id: 6,
      full_name: "Fiona Glenn",
      username: "fiona_g",
      age: 25,
      gender: "Female",
      subscription: "Free",
    },
    {
      id: 7,
      full_name: "George Miller",
      username: "george_m",
      age: 51,
      gender: "Male",
      subscription: "Premium",
    },
    {
      id: 8,
      full_name: "Hannah Lee",
      username: "hannah_l",
      age: 19,
      gender: "Female",
      subscription: "Free",
    },
    {
      id: 9,
      full_name: "Ivy Ross",
      username: "ivy_r",
      age: 33,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 10,
      full_name: "Jack Sparrow",
      username: "jack_s",
      age: 45,
      gender: "Male",
      subscription: "Free",
    },
    // Add more mock users to reach the total_users count (45 total)
    {
      id: 11,
      full_name: "Kelly Chen",
      username: "kelly_c",
      age: 29,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 12,
      full_name: "Liam Neeson",
      username: "liam_n",
      age: 60,
      gender: "Male",
      subscription: "Premium",
    },
    {
      id: 13,
      full_name: "Mia Toretto",
      username: "mia_t",
      age: 37,
      gender: "Female",
      subscription: "Free",
    },
    {
      id: 14,
      full_name: "Noah Smith",
      username: "noah_s",
      age: 24,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 15,
      full_name: "Olivia White",
      username: "olivia_w",
      age: 26,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 16,
      full_name: "Peter Quill",
      username: "peter_q",
      age: 35,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 17,
      full_name: "Quinn Fabray",
      username: "quinn_f",
      age: 23,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 18,
      full_name: "Ryan Gosling",
      username: "ryan_g",
      age: 42,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 19,
      full_name: "Sarah Conor",
      username: "sarah_c",
      age: 38,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 20,
      full_name: "Tom Hardy",
      username: "tom_h",
      age: 47,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 21,
      full_name: "Uma Thurman",
      username: "uma_t",
      age: 53,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 22,
      full_name: "Victor Stone",
      username: "victor_s",
      age: 21,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 23,
      full_name: "Wendy Testaburger",
      username: "wendy_t",
      age: 20,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 24,
      full_name: "Xavier Woods",
      username: "xavier_w",
      age: 31,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 25,
      full_name: "Yara Flor",
      username: "yara_f",
      age: 27,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 26,
      full_name: "Zane Malik",
      username: "zane_m",
      age: 36,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 27,
      full_name: "Ava Dubois",
      username: "ava_d",
      age: 29,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 28,
      full_name: "Ben Carter",
      username: "ben_c",
      age: 32,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 29,
      full_name: "Chloe Foster",
      username: "chloe_f",
      age: 24,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 30,
      full_name: "Dan Evans",
      username: "dan_e",
      age: 41,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 31,
      full_name: "Ella Garcia",
      username: "ella_g",
      age: 28,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 32,
      full_name: "Finn Howard",
      username: "finn_h",
      age: 33,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 33,
      full_name: "Grace Irwin",
      username: "grace_i",
      age: 25,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 34,
      full_name: "Henry Jones",
      username: "henry_j",
      age: 44,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 35,
      full_name: "Isla King",
      username: "isla_k",
      age: 20,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 36,
      full_name: "Jake Lee",
      username: "jake_l",
      age: 30,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 37,
      full_name: "Kara Miller",
      username: "kara_m",
      age: 39,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 38,
      full_name: "Leo Norris",
      username: "leo_n",
      age: 50,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 39,
      full_name: "Maya Ortiz",
      username: "maya_o",
      age: 27,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 40,
      full_name: "Nolan Poe",
      username: "nolan_p",
      age: 34,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 41,
      full_name: "Phoebe Quinn",
      username: "phoebe_q",
      age: 26,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 42,
      full_name: "Quentin Riley",
      username: "quentin_r",
      age: 43,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 43,
      full_name: "Rachel Scott",
      username: "rachel_s",
      age: 29,
      gender: "Female",
      subscription: "Premium",
    },
    {
      id: 44,
      full_name: "Sam Taylor",
      username: "sam_t",
      age: 31,
      gender: "Male",
      subscription: "Free",
    },
    {
      id: 45,
      full_name: "Tess Underhill",
      username: "tess_u",
      age: 22,
      gender: "Female",
      subscription: "Premium",
    },
  ],
};
